import type { Recommendation, User } from '@/types'

const mockUser1: User = {
  id: '1',
  username: 'sofi',
  displayName: 'Sofía',
  avatarUrl: null,
  bio: 'películas, libros y demasiado café ☕',
  favoriteMedia: [],
  followersCount: 142,
  followingCount: 89,
  createdAt: '2024-01-15T00:00:00Z',
}

const mockUser2: User = {
  id: '2',
  username: 'vale',
  displayName: 'Valentina',
  avatarUrl: null,
  bio: 'colecciono sentimientos y películas de llanto 🌧️',
  favoriteMedia: [],
  followersCount: 203,
  followingCount: 117,
  createdAt: '2024-02-20T00:00:00Z',
}

const mockUser3: User = {
  id: '3',
  username: 'cami',
  displayName: 'Camila',
  avatarUrl: null,
  bio: 'playlists para cada estado de ánimo 🎵',
  favoriteMedia: [],
  followersCount: 78,
  followingCount: 65,
  createdAt: '2024-03-10T00:00:00Z',
}

export const mockRecommendations: Recommendation[] = [
  {
    id: '1',
    userId: '2',
    user: mockUser2,
    type: 'movie',
    title: 'Past Lives',
    subtitle: 'Celine Song, 2023',
    description: 'lo vi después de una semana muy dura. necesitaba llorar sin saber por qué. esto lo fue.',
    coverUrl: 'https://image.tmdb.org/t/p/w500/k3waqVXSnäppsbärgöatten.jpg',
    rating: 5,
    moodTags: ['crying', 'healing', 'romantic'],
    source: 'tmdb',
    externalId: '1115623',
    externalMetadata: {
      releaseYear: 2023,
      genres: ['Drama', 'Romance'],
    },
    likesCount: 24,
    commentsCount: 8,
    savesCount: 15,
    isPublic: true,
    isLiked: false,
    isSaved: false,
    collectionIds: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: '2',
    userId: '3',
    user: mockUser3,
    type: 'album',
    title: 'Sling',
    subtitle: 'Clairo',
    description: 'esta es mi playlist de domingos lluviosos. no hay nada más a agregar.',
    coverUrl: '',
    rating: 4.5,
    moodTags: ['cozy', 'rainy night', 'soft girl'],
    source: 'spotify',
    externalId: '4m2880jivSbbyEGAKfITCa',
    externalMetadata: {
      artistName: 'Clairo',
    },
    likesCount: 31,
    commentsCount: 5,
    savesCount: 22,
    isPublic: true,
    isLiked: true,
    isSaved: true,
    collectionIds: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
  {
    id: '3',
    userId: '1',
    user: mockUser1,
    type: 'book',
    title: 'Normal People',
    subtitle: 'Sally Rooney',
    description: 'no entendí por qué me hizo tanto daño hasta que lo terminé.',
    coverUrl: '',
    rating: 4,
    moodTags: ['heartbreak', 'dark academia', 'nostalgic'],
    source: 'google_books',
    externalId: 'normal-people',
    externalMetadata: {
      authorName: 'Sally Rooney',
      pageCount: 273,
    },
    likesCount: 18,
    commentsCount: 12,
    savesCount: 9,
    isPublic: true,
    isLiked: false,
    isSaved: false,
    collectionIds: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 14).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 14).toISOString(),
  },
]
